### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by stev-0** [hiasinho/Leaflet.vector-markers#11]
I'm not sure if this was a quirk of my setup, but I had to put a high z-index on my icon. Should this not be in the CSS somewhere to make sure the icon is always higher than the marker?

**Comment by sookoll** [comment]
Confirm. Marker itself has z-index: 200 and icon are not visible by default. I had to set fa class z-index: 201 to make it visible.

**Comment by hiasinho** [comment]
Should be good now. At least the examples work for me.
