### ISSUE TITLE
Performance for maps with hundreds or even thousands of markers

### ISSUE THREAD

**Issue by tdaubs** [hiasinho/Leaflet.vector-markers#14]
It would be interesting to see how well the different browsers handled vector markers with hundreds or even thousands of points on a map. Has anyone tested this use case with vector markers?

**Comment by hiasinho** [comment]
A marker is just a tag in the document. So it shouldn't be different from other tags with events attached to them. You can clone the repo and adjust the file `examples/js/index.js` to add thousands of markers. Then just run `npm run examples`.
