### ISSUE TITLE
Unable to install last version with bower

### ISSUE THREAD

**Issue by CGGGO** [hiasinho/Leaflet.vector-markers#18]
EMALFORMED Failed to read

**Comment by elesdoar** [comment]
Error, extra comma in https://github.com/hiasinho/Leaflet.vector-markers/blob/0.0.5/bower.json#L28

**Comment by jfsebastian** [comment]
I've forked and fixed the issue.
As a temporary solution, until @hiasinho changes it, it's possible to install it from my last commit:
`bower install https://github.com/jfsebastian/Leaflet.vector-markers.git#7a0c707c2cf2f758f57329772ca6f26a1de27452`

**Comment by hiasinho** [comment]
Merged the PR. Sorry for the late answer.
