### ISSUE TITLE
smaller icon?

### ISSUE THREAD

**Issue by calvin1978** [hiasinho/Leaflet.vector-markers#5]
vector markers  provide the best icon set, but can it set to smaller like the normal markers?

**Comment by hiasinho** [comment]
Should be possible to make icons smaller by changing the sizes in https://github.com/hiasinho/Leaflet.vector-markers/blob/master/src/Leaflet.vector-markers.coffee#L48.

I'll put that option on the next release. Not sure when I release it.

**Comment by calvinxiu** [comment]
thanks, i had hard code it, and the css file also need to updated.

**Comment by hiasinho** [comment]
Try:

```js
L.marker([48.15391,11.53283], { icon: L.VectorMarkers.icon({
  viewBox: '0 0 32 52',
  iconSize: [30 * 0.75, 50 * 0.75],
  iconAnchor: [ 15 * 0.75, 50 * 0.75 ],
  icon: 'rocket',
  prefix: 'fa',
  markerColor: '#002b36',
  iconColor: '#eee8d5'
})}).addTo(map)
```
