### ISSUE TITLE
change L.VectorMarkers.MAP_PIN

### ISSUE THREAD

**Issue by pere** [hiasinho/Leaflet.vector-markers#6]
I am trying to apply a different path (ex: http://map-icons.com/#markers), for example:
M 50 -119.876 -50 -119.876 -50 -19.876 -13.232 -19.876 0.199 0 13.63 -19.876 50 -19.876 Z
I wonder why it does not work? (almost no idea about SVG...)

**Comment by adriennn** [comment]
it's working fine for me, are you modifying the svg path in the source js or in the minified version? And which one are you calling in your webpage?

**Comment by hiasinho** [comment]
I got it working like this:

```js
L.marker([48.15391,11.53283], { icon: L.VectorMarkers.icon({
  map_pin: map_pin,
  viewBox: '0 0 36 48',
  iconSize: [36, 48],
  iconAnchor: [ 18, 50 ],
  icon: 'rocket',
  prefix: 'fa',
  markerColor: '#002b36',
  iconColor: '#eee8d5'
})}).addTo(map)
```
